In [1]:
import numpy as np

In [3]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [4]:
a = np.array([[1,2,3],
              [4,5,6]])

a

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
a1 = np.array([1,2,3], dtype=float)
a1

array([1., 2., 3.])

In [6]:
a1 = np.arange(5)
a1

array([0, 1, 2, 3, 4])

In [7]:
a2 = np.arange(4, 16, 3)

a2

array([ 4,  7, 10, 13])

In [8]:
a1 = np.arange(1,9)
a2 = np.arange(16).reshape(4,4)
a3 = np.arange(27).reshape(3,3,3)

In [9]:
a1

array([1, 2, 3, 4, 5, 6, 7, 8])

In [10]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [11]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [12]:
np.zeros(3)

array([0., 0., 0.])

In [13]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((2))

array([1., 1.])

In [16]:
np.random.random((4,5))

array([[0.94583651, 0.91865591, 0.79384166, 0.2179133 , 0.69351725],
       [0.20460346, 0.40296571, 0.66559464, 0.83605575, 0.02325131],
       [0.13383535, 0.56087509, 0.28812331, 0.26606963, 0.14722311],
       [0.3846245 , 0.56176146, 0.88578615, 0.50283836, 0.55765522]])

In [ ]:
np.linspace(1, 15, 4)

array([ 1.        ,  5.66666667, 10.33333333, 15.        ])

In [22]:
np.int32(np.linspace(1, 15, 4))

array([ 1,  5, 10, 15], dtype=int32)

In [48]:
np.linspace(1,15,3, dtype=float)

array([ 1.,  8., 15.])

In [23]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [25]:
a2.ndim

2

In [26]:
a3.ndim

3

In [27]:
a3.shape

(3, 3, 3)

In [28]:
a1.size

8

In [29]:
a3.size

27

In [30]:
a2.dtype

dtype('int64')

In [37]:
a1 = a1.astype(np.int32)

In [41]:
a1.itemsize

4

In [43]:
a2.itemsize

8

In [44]:
a3.itemsize

8

In [45]:
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
int64
int64


In [46]:
np.arange(16).reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [49]:
a1

array([1, 2, 3, 4, 5, 6, 7, 8], dtype=int32)

In [50]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [51]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [52]:
a1 + 2

array([ 3,  4,  5,  6,  7,  8,  9, 10], dtype=int32)

In [53]:
a2 * 2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22],
       [24, 26, 28, 30]])

In [54]:
a3 // 2

array([[[ 0,  0,  1],
        [ 1,  2,  2],
        [ 3,  3,  4]],

       [[ 4,  5,  5],
        [ 6,  6,  7],
        [ 7,  8,  8]],

       [[ 9,  9, 10],
        [10, 11, 11],
        [12, 12, 13]]])

In [55]:
a1 * a1

array([ 1,  4,  9, 16, 25, 36, 49, 64], dtype=int32)

In [56]:
a1 * a2

ValueError: operands could not be broadcast together with shapes (8,) (4,4) 

In [57]:
a = np.arange(8, dtype=np.int32)
b = np.arange(12, dtype=np.int64)

In [58]:
a + b

ValueError: operands could not be broadcast together with shapes (8,) (12,) 

In [63]:
a = np.arange(8, dtype=np.int32)
b = np.arange(10, 18, dtype=np.int64)

print((a+b).dtype)
a + b

int64


array([10, 12, 14, 16, 18, 20, 22, 24])

In [64]:
np.max(a1)

np.int32(8)

In [65]:
np.min(a2)

np.int64(0)

In [66]:
np.max(a3)

np.int64(26)

In [67]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [72]:
np.max(a3,axis = 1)

array([[ 6,  7,  8],
       [15, 16, 17],
       [24, 25, 26]])

In [73]:
np.min(a2, axis=0)

array([0, 1, 2, 3])

In [74]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [75]:
np.min(a2, axis=1)

array([ 0,  4,  8, 12])

In [76]:
np.mean(a1)

np.float64(4.5)

In [77]:
np.mean(a3)

np.float64(13.0)

In [78]:
np.median(a3)

np.float64(13.0)

In [80]:
np.std(a3,dtype=np.int32)

np.int32(7)

In [83]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(22, 34).reshape(4,3)


In [84]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [85]:
a2

array([[22, 23, 24],
       [25, 26, 27],
       [28, 29, 30],
       [31, 32, 33]])

In [86]:
np.dot(a1, a2)

array([[ 174,  180,  186],
       [ 598,  620,  642],
       [1022, 1060, 1098]])

In [87]:
np.log(a1)

C:\Users\kshit\AppData\Local\Temp\ipykernel_11280\2387409814.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(a1)


array([[      -inf, 0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947, 1.94591015],
       [2.07944154, 2.19722458, 2.30258509, 2.39789527]])

In [88]:
np.exp(a2)

array([[3.58491285e+09, 9.74480345e+09, 2.64891221e+10],
       [7.20048993e+10, 1.95729609e+11, 5.32048241e+11],
       [1.44625706e+12, 3.93133430e+12, 1.06864746e+13],
       [2.90488497e+13, 7.89629602e+13, 2.14643580e+14]])

In [89]:
a1 = np.arange(1,9)
a2 = np.arange(16).reshape(4,4)
a3 = np.arange(27).reshape(3,3,3)

In [90]:
a1[1]

np.int64(2)

In [91]:
a1[:]

array([1, 2, 3, 4, 5, 6, 7, 8])

In [92]:
a1[:5]

array([1, 2, 3, 4, 5])

In [93]:
a2[2]

array([ 8,  9, 10, 11])

In [94]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [96]:
a2[:3:2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [97]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [98]:
np.transpose(a3)

array([[[ 0,  9, 18],
        [ 3, 12, 21],
        [ 6, 15, 24]],

       [[ 1, 10, 19],
        [ 4, 13, 22],
        [ 7, 16, 25]],

       [[ 2, 11, 20],
        [ 5, 14, 23],
        [ 8, 17, 26]]])

In [99]:
a3.T

array([[[ 0,  9, 18],
        [ 3, 12, 21],
        [ 6, 15, 24]],

       [[ 1, 10, 19],
        [ 4, 13, 22],
        [ 7, 16, 25]],

       [[ 2, 11, 20],
        [ 5, 14, 23],
        [ 8, 17, 26]]])

In [100]:
a2.T

array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])

In [103]:
a1 = np.arange(12).reshape(4,3)
a2 = np.arange(10, 22).reshape(4,3)

In [104]:
a2

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [105]:
a1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [106]:
np.hstack((a2,a1))

array([[10, 11, 12,  0,  1,  2],
       [13, 14, 15,  3,  4,  5],
       [16, 17, 18,  6,  7,  8],
       [19, 20, 21,  9, 10, 11]])

In [107]:
np.hstack((a1,a2,a1))

array([[ 0,  1,  2, 10, 11, 12,  0,  1,  2],
       [ 3,  4,  5, 13, 14, 15,  3,  4,  5],
       [ 6,  7,  8, 16, 17, 18,  6,  7,  8],
       [ 9, 10, 11, 19, 20, 21,  9, 10, 11]])

In [108]:
np.vstack((a1,a2))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [111]:
np.hsplit(a1,3)

[array([[0],
        [3],
        [6],
        [9]]),
 array([[ 1],
        [ 4],
        [ 7],
        [10]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11]])]