In [1]:
import numpy as np

In [8]:
a = np.random.randint(0,55,size=15)

In [9]:
a

array([ 0, 27, 33, 25, 29, 41, 51, 51, 42, 11, 50, 52, 11, 52, 48],
      dtype=int32)

In [10]:
np.sort(a)

array([ 0, 11, 11, 25, 27, 29, 33, 41, 42, 48, 50, 51, 51, 52, 52],
      dtype=int32)

In [11]:
b = np.random.randint(0,100,size=36).reshape(6,6)

In [12]:
b

array([[ 0, 44, 68, 18, 79, 49],
       [93, 79, 13, 95, 74,  7],
       [34, 13, 20, 35, 10, 41],
       [65, 79, 54, 36, 99,  9],
       [17, 70, 71, 73, 61,  5],
       [21,  3, 77, 81, 89, 72]], dtype=int32)

In [13]:
np.sort(b)

array([[ 0, 18, 44, 49, 68, 79],
       [ 7, 13, 74, 79, 93, 95],
       [10, 13, 20, 34, 35, 41],
       [ 9, 36, 54, 65, 79, 99],
       [ 5, 17, 61, 70, 71, 73],
       [ 3, 21, 72, 77, 81, 89]], dtype=int32)

In [14]:
np.sort(b,axis=0)

array([[ 0,  3, 13, 18, 10,  5],
       [17, 13, 20, 35, 61,  7],
       [21, 44, 54, 36, 74,  9],
       [34, 70, 68, 73, 79, 41],
       [65, 79, 71, 81, 89, 49],
       [93, 79, 77, 95, 99, 72]], dtype=int32)

In [15]:
# np.append

np.append(a, 200)

array([  0,  27,  33,  25,  29,  41,  51,  51,  42,  11,  50,  52,  11,
        52,  48, 200])

In [16]:
np.append(b, 200)

array([  0,  44,  68,  18,  79,  49,  93,  79,  13,  95,  74,   7,  34,
        13,  20,  35,  10,  41,  65,  79,  54,  36,  99,   9,  17,  70,
        71,  73,  61,   5,  21,   3,  77,  81,  89,  72, 200])

In [23]:
np.append(b,np.array([[1,1,1,1,1,1]]), axis=0)

array([[ 0, 44, 68, 18, 79, 49],
       [93, 79, 13, 95, 74,  7],
       [34, 13, 20, 35, 10, 41],
       [65, 79, 54, 36, 99,  9],
       [17, 70, 71, 73, 61,  5],
       [21,  3, 77, 81, 89, 72],
       [ 1,  1,  1,  1,  1,  1]])

In [24]:
# np.concatenate
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [27]:
np.concatenate((c,d), axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [28]:
# np.unique
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

In [29]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

In [31]:
# expand dimensions: np.expand_dims

a.shape

(15,)

In [32]:
np.expand_dims(a, axis=0)

array([[ 0, 27, 33, 25, 29, 41, 51, 51, 42, 11, 50, 52, 11, 52, 48]],
      dtype=int32)

In [33]:
np.expand_dims(a, axis=1)

array([[ 0],
       [27],
       [33],
       [25],
       [29],
       [41],
       [51],
       [51],
       [42],
       [11],
       [50],
       [52],
       [11],
       [52],
       [48]], dtype=int32)

In [34]:
# np.where

a

array([ 0, 27, 33, 25, 29, 41, 51, 51, 42, 11, 50, 52, 11, 52, 48],
      dtype=int32)

In [35]:
np.where(a>10)

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]),)

In [36]:
np.where(~(a%2 == 0), 0, a)

array([ 0,  0,  0,  0,  0,  0,  0,  0, 42,  0, 50, 52,  0, 52, 48],
      dtype=int32)

In [39]:
a = np.random.randint(1,100,20)

In [41]:
## np.argmax

np.argmax(a)

np.int64(1)

In [40]:
a

array([17, 99, 98, 79, 99, 24, 73, 37, 28, 24, 73, 40, 62,  5, 23, 72,  8,
       89, 91, 53], dtype=int32)

In [42]:
b

array([[ 0, 44, 68, 18, 79, 49],
       [93, 79, 13, 95, 74,  7],
       [34, 13, 20, 35, 10, 41],
       [65, 79, 54, 36, 99,  9],
       [17, 70, 71, 73, 61,  5],
       [21,  3, 77, 81, 89, 72]], dtype=int32)

In [43]:
np.argmax(b)

np.int64(22)

In [45]:
np.argmax(b,axis=0)

array([1, 1, 5, 1, 3, 5])

In [46]:
np.argmax(b,axis=1)

array([4, 3, 5, 4, 3, 4])

In [47]:
# np.argmin

np.argmin(a)

np.int64(13)

In [48]:
# np.cumsum

np.cumsum(a)

array([  17,  116,  214,  293,  392,  416,  489,  526,  554,  578,  651,
        691,  753,  758,  781,  853,  861,  950, 1041, 1094])

In [50]:
np.cumsum(b,axis=0)

array([[  0,  44,  68,  18,  79,  49],
       [ 93, 123,  81, 113, 153,  56],
       [127, 136, 101, 148, 163,  97],
       [192, 215, 155, 184, 262, 106],
       [209, 285, 226, 257, 323, 111],
       [230, 288, 303, 338, 412, 183]])

In [51]:
# np.cumprod

np.cumprod(a)

array([                  17,                 1683,               164934,
                   13029786,           1289948814,          30958771536,
              2259990322128,       83619641918736,     2341349973724608,
          56192399369390592,  4102045153965513216, -1938890504765435904,
        8915997220509835264,  7686497955130073088, -7677987769103835136,
         587202835810418688,  4697622686483349504, -6186694598301581312,
        8859857839552200704,  8403863653527846912])

In [52]:
# np.percentile

a

array([17, 99, 98, 79, 99, 24, 73, 37, 28, 24, 73, 40, 62,  5, 23, 72,  8,
       89, 91, 53], dtype=int32)

In [53]:
np.percentile(a, 50)

np.float64(57.5)

In [54]:
np.median(a)

np.float64(57.5)

In [57]:
## np.historgram
a

array([17, 99, 98, 79, 99, 24, 73, 37, 28, 24, 73, 40, 62,  5, 23, 72,  8,
       89, 91, 53], dtype=int32)

In [58]:
print(np.min(a))
print(np.max(a))

5
99


In [56]:
np.histogram(a, bins=10)

(array([2, 2, 3, 2, 0, 1, 1, 4, 1, 4]),
 array([ 5. , 14.4, 23.8, 33.2, 42.6, 52. , 61.4, 70.8, 80.2, 89.6, 99. ]))

In [59]:
## np.corrcoef

salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])


np.corrcoef(salary, experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

In [60]:
# np.isin
a

array([17, 99, 98, 79, 99, 24, 73, 37, 28, 24, 73, 40, 62,  5, 23, 72,  8,
       89, 91, 53], dtype=int32)

In [61]:
np.isin(a, [1,5,7,10,15])

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False,  True, False, False, False, False,
       False, False])

In [62]:
a[np.isin(a, [1,5,7,10,15])]

array([5], dtype=int32)

In [63]:
# np.flip

np.flip(a)

array([53, 91, 89,  8, 72, 23,  5, 62, 40, 73, 24, 28, 37, 73, 24, 99, 79,
       98, 99, 17], dtype=int32)

In [64]:
b

array([[ 0, 44, 68, 18, 79, 49],
       [93, 79, 13, 95, 74,  7],
       [34, 13, 20, 35, 10, 41],
       [65, 79, 54, 36, 99,  9],
       [17, 70, 71, 73, 61,  5],
       [21,  3, 77, 81, 89, 72]], dtype=int32)

In [65]:
np.flip(b)

array([[72, 89, 81, 77,  3, 21],
       [ 5, 61, 73, 71, 70, 17],
       [ 9, 99, 36, 54, 79, 65],
       [41, 10, 35, 20, 13, 34],
       [ 7, 74, 95, 13, 79, 93],
       [49, 79, 18, 68, 44,  0]], dtype=int32)

In [66]:
np.flip(b,axis=0)

array([[21,  3, 77, 81, 89, 72],
       [17, 70, 71, 73, 61,  5],
       [65, 79, 54, 36, 99,  9],
       [34, 13, 20, 35, 10, 41],
       [93, 79, 13, 95, 74,  7],
       [ 0, 44, 68, 18, 79, 49]], dtype=int32)

In [67]:
# np.put

np.put(a, [0,1,2], [100,200,300])

In [72]:
a

array([100, 200, 300,  79,  99,  24,  73,  37,  28,  24,  73,  40,  62,
         5,  23,  72,   8,  89,  91,  53], dtype=int32)

In [73]:
# np.delete

np.delete(a, [0,2,5,10])

array([200,  79,  99,  73,  37,  28,  24,  40,  62,   5,  23,  72,   8,
        89,  91,  53], dtype=int32)

#### Set Functions

In [74]:
# np.union1d

a = np.array([1,2,3,4,5,6])
b = np.array([4,5,6,7,8,9])

np.union1d(a,b)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [75]:
np.intersect1d(a,b)

array([4, 5, 6])

In [76]:
np.setdiff1d(a,b)

array([1, 2, 3])

In [77]:
np.setxor1d(b,a)

array([1, 2, 3, 7, 8, 9])

In [78]:
np.in1d(a, [2,3,8])

C:\Users\kshit\AppData\Local\Temp\ipykernel_17920\2598385744.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  np.in1d(a, [2,3,8])


array([False,  True,  True, False, False, False])

In [79]:
a[np.in1d(a, [2,3,8])]

C:\Users\kshit\AppData\Local\Temp\ipykernel_17920\849335983.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  a[np.in1d(a, [2,3,8])]


array([2, 3])

In [81]:
# np.clip

a = np.array([17, 99, 98, 79, 99, 24, 73, 37, 28, 24, 73, 40, 62,  5, 23, 72,  8,
       89, 91, 53])

In [82]:
a

array([17, 99, 98, 79, 99, 24, 73, 37, 28, 24, 73, 40, 62,  5, 23, 72,  8,
       89, 91, 53])

In [83]:
np.clip(a, a_min=20, a_max=80)

array([20, 80, 80, 79, 80, 24, 73, 37, 28, 24, 73, 40, 62, 20, 23, 72, 20,
       80, 80, 53])